'''
all data scraped from
https://en.wikipedia.org/wiki/Chemical_element
up-to-date as of 2019.11.25
see notebook A1 for details on how this information was gathered
'''

import numpy as np

symbols = ('e-',
    'H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg', 'Al',
    'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe',
    'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr',
    'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn',
    'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm',
    'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Hf', 'Ta', 'W',
    'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn',
    'Fr', 'Ra', 'Ac', 'Th', 'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf',
    'Es', 'Fm', 'Md', 'No', 'Lr', 'Rf', 'Db', 'Sg', 'Bh', 'Hs', 'Mt', 'Ds',
    'Rg', 'Cn', 'Nh', 'Fl', 'Mc', 'Lv', 'Ts', 'Og'
    )

names = ('negative charge',
    'Hydrogen', 'Helium', 'Lithium', 'Beryllium', 'Boron', 'Carbon',
    'Nitrogen', 'Oxygen', 'Fluorine', 'Neon', 'Sodium', 'Magnesium',
    'Aluminium', 'Silicon', 'Phosphorus', 'Sulfur', 'Chlorine', 'Argon',
    'Potassium', 'Calcium', 'Scandium', 'Titanium', 'Vanadium', 'Chromium',
    'Manganese', 'Iron', 'Cobalt', 'Nickel', 'Copper', 'Zinc', 'Gallium',
    'Germanium', 'Arsenic', 'Selenium', 'Bromine', 'Krypton', 'Rubidium',
    'Strontium', 'Yttrium', 'Zirconium', 'Niobium', 'Molybdenum',
    'Technetium', 'Ruthenium', 'Rhodium', 'Palladium', 'Silver', 'Cadmium',
    'Indium', 'Tin', 'Antimony', 'Tellurium', 'Iodine', 'Xenon', 'Caesium',
    'Barium', 'Lanthanum', 'Cerium', 'Praseodymium', 'Neodymium', 'Promethium',
    'Samarium', 'Europium', 'Gadolinium', 'Terbium', 'Dysprosium', 'Holmium',
    'Erbium', 'Thulium', 'Ytterbium', 'Lutetium', 'Hafnium', 'Tantalum',
    'Tungsten', 'Rhenium', 'Osmium', 'Iridium', 'Platinum', 'Gold', 'Mercury',
    'Thallium', 'Lead', 'Bismuth', 'Polonium', 'Astatine', 'Radon', 'Francium',
    'Radium', 'Actinium', 'Thorium', 'Protactinium', 'Uranium', 'Neptunium',
    'Plutonium', 'Americium', 'Curium', 'Berkelium', 'Californium',
    'Einsteinium', 'Fermium', 'Mendelevium', 'Nobelium', 'Lawrencium',
    'Rutherfordium', 'Dubnium', 'Seaborgium', 'Bohrium', 'Hassium',
    'Meitnerium', 'Darmstadtium', 'Roentgenium', 'Copernicium',
    'Nihonium', 'Flerovium', 'Moscovium', 'Livermorium', 'Tennessine',
    'Oganesson'
)

names_lower = tuple(n.lower() for n in names)

names_origin = ('Placeholder for index_0',
    "Greek elements hydro- and -gen, meaning 'water-forming'",
    "Greek hḗlios, 'sun'",
    "Greek líthos, 'stone'",
    'beryl, a mineral (ultimately from the name of Belur in southern India)',
    'borax, a mineral (from Arabic bawraq)',
    "Latin carbo, 'coal'",
    "Greek nítron and -gen, meaning 'niter-forming'",
    "Greek oxy- and -gen, meaning 'acid-forming'",
    "Latin fluere, 'to flow'",
    "Greek néon, 'new'",
    "English soda (the symbol Na is derived from New Latin natrium, coined from German Natron, 'natron')",
    'Magnesia, a district of Eastern Thessaly in Greece',
    "alumina, from Latin alumen (gen. aluminis), 'bitter salt, alum'",
    "Latin silex, 'flint' (originally silicium)",
    "Greek phōsphóros, 'light-bearing'",
    "Latin sulphur, 'brimstone'",
    "Greek chlōrós, 'greenish yellow'",
    "Greek argós, 'idle' (because of its inertness)",
    "New Latin potassa, 'potash' (the symbol K is derived from Latin kalium)",
    "Latin calx, 'lime'",
    "Latin Scandia, 'Scandinavia'",
    'Titans, the sons of the Earth goddess of Greek mythology',
    'Vanadis, an Old Norse name for the Scandinavian goddess Freyja',
    "Greek chróma, 'colour'",
    'corrupted from magnesia negra; see Magnesium',
    'English word (the symbol Fe is derived from Latin ferrum)',
    "German Kobold, 'goblin'",
    'Nickel, a mischievous sprite of German miner mythology',
    "English word, from Latin cuprum, from Ancient Greek Kýpros 'Cyprus'",
    "Most likely from German Zinke, 'prong' or 'tooth', though some suggest Persian sang, 'stone'",
    "Latin Gallia, 'France'",
    "Latin Germania, 'Germany'",
    "French arsenic, from Greek arsenikón 'yellow arsenic' (influenced by arsenikós, 'masculine' or 'virile'), from a West Asian wanderword ultimately from Old Iranian *zarniya-ka, 'golden'",
    "Greek selḗnē, 'moon'",
    "Greek brômos, 'stench'",
    "Greek kryptós, 'hidden'",
    "Latin rubidus, 'deep red'",
    'Strontian, a village in Scotland',
    'Ytterby, a village in Sweden',
    'zircon, a mineral',
    'Niobe, daughter of king Tantalus from Greek mythology',
    "Greek molýbdaina, 'piece of lead', from mólybdos, 'lead', due to confusuion with lead ore galena (PbS)",
    "Greek tekhnētós, 'artificial'",
    "New Latin Ruthenia, 'Russia'",
    "Greek rhodóeis, 'rose-coloured', from rhódon, 'rose'",
    'the asteroid Pallas, considered a planet at the time',
    'English word (The symbol is derived from Latin argentum)',
    'New Latin cadmia, from King Kadmos',
    "Latin indicum, 'indigo' (colour found in its spectrum)",
    'English word (The symbol is derived from Latin stannum)',
    "Latin antimonium, the origin of which is uncertain: folk etymologies suggest it is derived from Greek antí ('against') + mónos ('alone'), or Old French anti-moine, 'Monk's bane', but it could plausibly be from or related to Arabic ʾiṯmid, 'antimony', reformatted as a Latin word. (The symbol is derived from Latin stibium 'stibnite'.)",
    "Latin tellus, 'the ground, earth'",
    "French iode, from Greek ioeidḗs, 'violet')",
    "Greek xénon, neuter form of xénos 'strange'",
    "Latin caesius, 'sky-blue'",
    "Greek barýs, 'heavy'",
    "Greek lanthánein, 'to lie hidden'",
    'the dwarf planet Ceres, considered a planet at the time',
    "Greek prásios dídymos, 'green twin'",
    "Greek néos dídymos, 'new twin'",
    'Prometheus of Greek mythology',
    'samarskite, a mineral named after Colonel Vasili Samarsky-Bykhovets, Russian mine official',
    'Europe',
    'gadolinite, a mineral named after Johan Gadolin, Finnish chemist, physicist and mineralogist',
    'Ytterby, a village in Sweden',
    "Greek dysprósitos, 'hard to get'",
    "New Latin Holmia, 'Stockholm'",
    'Ytterby, a village in Sweden',
    'Thule, the ancient name for an unclear northern location',
    'Ytterby, a village in Sweden',
    "Latin Lutetia, 'Paris'",
    "New Latin Hafnia, 'Copenhagen' (from Danish havn)",
    'King Tantalus, father of Niobe from Greek mythology',
    "Swedish tung sten, 'heavy stone' (The symbol is from wolfram, the old name of the tungsten mineral wolframite)",
    "Latin Rhenus, 'the Rhine'",
    "Greek osmḗ, 'smell'",
    'Iris, the Greek goddess of the rainbow',
    "Spanish platina, 'little silver', from plata 'silver'",
    'English word (the symbol Au is derived from Latin aurum)',
    "Mercury, Roman god of commerce, communication, and luck, known for his speed and mobility (the symbol Hg derives from the element's Latin name hydrargyrum, from Greek hydrárgyros, 'water-silver')",
    "Greek thallós, 'green shoot or twig'",
    'English word (the symbol Pb is derived from Latin plumbum)',
    "German Wismut, from weiß Masse 'white mass', unless from Arabic",
    "Latin Polonia, 'Poland' (the home country of Marie Curie)",
    "Greek ástatos, 'unstable'",
    'radium',
    'France',
    "French radium, from Latin radius, 'ray'",
    "Greek aktís, 'ray'",
    'Thor, the Scandinavian god of thunder',
    "proto- (from Greek prôtos, 'first, before') + actinium, which is produced through the radioactive decay of protactinium",
    'Uranus, the seventh planet in the Solar System',
    'Neptune, the eighth planet in the Solar System',
    'the dwarf planet Pluto, considered the ninth planet in the Solar System at the time',
    'The Americas, as the element was first synthesised on the continent, by analogy with europium',
    'Pierre Curie and Marie Curie, French physicists and chemists',
    'Berkeley, California, where the element was first synthesised, by analogy with terbium',
    'California, where the element was first synthesised',
    'Albert Einstein, German physicist',
    'Enrico Fermi, Italian physicist',
    'Dmitri Mendeleev, Russian chemist and inventor who proposed the periodic table',
    'Alfred Nobel, Swedish chemist and engineer',
    'Ernest O. Lawrence, American physicist',
    'Ernest Rutherford, chemist and physicist from New Zealand',
    'Dubna, Russia, where the Joint Institute for Nuclear Research is located',
    'Glenn T. Seaborg, American chemist',
    'Niels Bohr, Danish physicist',
    "New Latin Hassia, 'Hesse' (a state in Germany)",
    'Lise Meitner, Austrian physicist',
    'Darmstadt, Germany, where the element was first synthesised',
    'Wilhelm Conrad Röntgen, German physicist',
    'Nicolaus Copernicus, Polish astronomer',
    "Japanese Nihon, 'Japan' (where the element was first synthesised)",
    'Flerov Laboratory of Nuclear Reactions, part of JINR, where the element was synthesised; itself named after Georgy Flyorov, Russian physicist',
    'Moscow Oblast, Russia, where the element was first synthesised',
    'Lawrence Livermore National Laboratory in Livermore, California, which collaborated with JINR on its synthesis',
    'Tennessee, United States (where Oak Ridge National Laboratory is located)',
    'Yuri Oganessian, Russian physicist'
)

groups = (np.nan,
    1, 18, 1, 2, 13, 14, 15, 16, 17, 18, 1, 2, 13, 14, 15, 16, 17, 18, 1, 2, 3,
    4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1, 2, 3, 4, 5, 6, 7,
    8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1, 2, 3, np.nan, np.nan, np.nan,
    np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan,
    np.nan, np.nan, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1, 2,
    3, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan,
    np.nan, np.nan, np.nan, np.nan, np.nan, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
    14, 15, 16, 17, 18
)

groups_cas = ((np.nan, ''),
    (1,'A'), (8,'A'), (1,'A'), (2,'A'), (3,'A'), (4,'A'), (5,'A'), (6,'A'),
    (7,'A'), (8,'A'), (1,'A'), (2,'A'), (3,'A'), (4,'A'), (5,'A'), (6,'A'),
    (7,'A'), (8,'A'), (1,'A'), (2,'A'), (3,'B'), (4,'B'), (5,'B'), (6,'B'),
    (7,'B'), (8,'B'), (8,'B'), (8,'B'), (1,'B'), (2,'B'), (3,'A'), (4,'A'),
    (5,'A'), (6,'A'), (7,'A'), (8,'A'), (1,'A'), (2,'A'), (3,'B'), (4,'B'),
    (5,'B'), (6,'B'), (7,'B'), (8,'B'), (8,'B'), (8,'B'), (1,'B'), (2,'B'),
    (3,'A'), (4,'A'), (5,'A'), (6,'A'), (7,'A'), (8,'A'), (1,'A'), (2,'A'),
    (3,'B'), np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan,
    np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, (4,'B'), (5,'B'), (6,'B'),
    (7,'B'), (8,'B'), (8,'B'), (8,'B'), (1,'B'), (2,'B'), (3,'A'), (4,'A'),
    (5,'A'), (6,'A'), (7,'A'), (8,'A'), (1,'A'), (2,'A'), (3,'B'), np.nan,
    np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan,
    np.nan, np.nan, np.nan, np.nan, (4,'B'), (5,'B'), (6,'B'), (7,'B'),
    (8,'B'), (8,'B'), (8,'B'), (1,'B'), (2,'B'), (3,'A'), (4,'A'), (5,'A'),
    (6,'A'), (7,'A'), (8,'A')
)

periods = (np.nan,
    1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7
)

relative_atomic_masses = (5.4858E-4,
    1.008, 4.002602, 6.94, 9.0121831, 10.81, 12.011, 14.007, 15.999,
    18.998403163, 20.1797, 22.98976928, 24.305, 26.9815384, 28.085,
    30.973761998, 32.06, 35.45, 39.948, 39.0983, 40.078, 44.955908, 47.867,
    50.9415, 51.9961, 54.938043, 55.845, 58.933194, 58.6934, 63.546, 65.38,
    69.723, 72.63, 74.921595, 78.971, 79.904, 83.798, 85.4678, 87.62, 88.90584,
    91.224, 92.90637, 95.95, 98, 101.07, 102.90549, 106.42, 107.8682, 112.414,
    114.818, 118.71, 121.76, 127.6, 126.90447, 131.293, 132.90545196, 137.327,
    138.90547, 140.116, 140.90766, 144.242, 145, 150.36, 151.964, 157.25,
    158.925354, 162.5, 164.930328, 167.259, 168.934218, 173.045, 174.9668,
    178.49, 180.94788, 183.84, 186.207, 190.23, 192.217, 195.084, 196.96657,
    200.592, 204.38, 207.2, 208.9804, 209, 210, 222, 223, 226, 227, 232.0377,
    231.03588, 238.02891, 237, 244, 243, 247, 247, 251, 252, 257, 258, 259,
    266, 267, 268, 269, 270, 270, 278, 281, 282, 285, 286, 289, 290, 293, 294,
    294
)

electronegativities = (np.nan,
    2.2, np.nan, 0.98, 1.57, 2.04, 2.55, 3.04, 3.44, 3.98, np.nan, 0.93, 1.31,
    1.61,1.9, 2.19, 2.58, 3.16, np.nan, 0.82, 1.0, 1.36, 1.54, 1.63, 1.66,
    1.55, 1.83,1.88, 1.91, 1.9, 1.65, 1.81, 2.01, 2.18, 2.55, 2.96, 3.0, 0.82,
    0.95, 1.22, 1.33, 1.6, 2.16, 1.9, 2.2, 2.28, 2.2, 1.93, 1.69, 1.78, 1.96,
    2.05, 2.1, 2.66, 2.6, 0.79, 0.89, 1.1, 1.12, 1.13, 1.14, 1.13, 1.17, 1.2,
    1.2, 1.2, 1.22, 1.23, 1.24, 1.25, 1.1, 1.27, 1.3, 1.5, 2.36, 1.9, 2.2, 2.2,
    2.28, 2.54, 2.0, 1.62, 1.87, 2.02, 2.0, 2.2, 2.2, 0.7, 0.9, 1.1, 1.3, 1.5,
    1.38, 1.36, 1.28, 1.13, 1.28, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, np.nan,
    np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan,
    np.nan, np.nan, np.nan, np.nan, np.nan
)